name: madrs-ai
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - pytorch
  - pytorch-cuda=11.8
  - torchaudio
  - torchvision
  - transformers
  - accelerate
  - ipykernel
  - librosa
  - ffmpeg
  - ipywidgets
  - gitpython
  - bitsandbytes
  - pip:
    - pyannote.audio
    - llama-cpp-python
