name: MADRS-transcribe
channels:
  - pytorch
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - absl-py=2.1.0
  - aiohttp=3.9.1
  - aiosignal=1.3.1
  - anyio=4.2.0
  - aom=3.7.1
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asttokens=2.4.1
  - astunparse=1.6.3
  - async-lru=2.0.4
  - attrs=23.2.0
  - audioread=3.0.1
  - aws-c-auth=0.7.11
  - aws-c-cal=0.6.9
  - aws-c-common=0.9.12
  - aws-c-compression=0.2.17
  - aws-c-event-stream=0.4.1
  - aws-c-http=0.8.0
  - aws-c-io=0.14.0
  - aws-c-mqtt=0.10.1
  - aws-c-s3=0.4.9
  - aws-c-sdkutils=0.1.13
  - aws-checksums=0.1.17
  - aws-crt-cpp=0.26.0
  - aws-sdk-cpp=1.11.210
  - babel=2.14.0
  - beautifulsoup4=4.12.3
  - blas=1.0
  - bleach=6.1.0
  - blinker=1.7.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.26.0
  - ca-certificates=2023.11.17
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=5.3.2
  - cairo=1.18.0
  - certifi=2023.11.17
  - cffi=1.16.0
  - charset-normalizer=3.3.2
  - click=8.1.7
  - colorama=0.4.6
  - comm=0.2.1
  - contourpy=1.2.0
  - cpuonly=2.0
  - cryptography=42.0.2
  - cycler=0.12.1
  - datasets=2.16.1
  - dav1d=1.2.1
  - debugpy=1.8.0
  - decorator=5.1.1
  - defusedxml=0.7.1
  - dill=0.3.7
  - entrypoints=0.4
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - expat=2.5.0
  - ffmpeg=6.1.1
  - filelock=3.13.1
  - flatbuffers=23.5.26
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.47.2
  - fqdn=1.5.1
  - freetype=2.12.1
  - fribidi=1.0.10
  - frozenlist=1.4.1
  - fsspec=2023.10.0
  - gast=0.5.4
  - gettext=0.21.1
  - gflags=2.2.2
  - giflib=5.2.1
  - glog=0.6.0
  - gmp=6.3.0
  - gmpy2=2.1.2
  - gnutls=3.7.9
  - google-auth=2.27.0
  - google-auth-oauthlib=1.2.0
  - google-pasta=0.2.0
  - graphite2=1.3.13
  - grpcio=1.59.3
  - h5py=3.10.0
  - harfbuzz=8.3.0
  - hdf5=1.14.3
  - huggingface_hub=0.20.2
  - icu=73.2
  - idna=3.6
  - importlib-metadata=7.0.1
  - importlib_metadata=7.0.1
  - importlib_resources=6.1.1
  - ipykernel=6.29.0
  - ipython=8.20.0
  - ipywidgets=8.1.1
  - isoduration=20.11.0
  - jedi=0.19.1
  - jinja2=3.1.3
  - joblib=1.3.2
  - json5=0.9.14
  - jsonpointer=2.4
  - jsonschema=4.21.1
  - jsonschema-specifications=2023.12.1
  - jsonschema-with-format-nongpl=4.21.1
  - jupyter-lsp=2.2.2
  - jupyter_client=8.6.0
  - jupyter_core=5.7.1
  - jupyter_events=0.9.0
  - jupyter_server=2.12.5
  - jupyter_server_terminals=0.5.2
  - jupyterlab=4.0.12
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.25.2
  - jupyterlab_widgets=3.0.9
  - keras=2.15.0
  - keyutils=1.6.1
  - kiwisolver=1.4.5
  - krb5=1.21.2
  - lame=3.100
  - lazy_loader=0.3
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20230802.1
  - libaec=1.1.2
  - libarrow=15.0.0
  - libarrow-acero=15.0.0
  - libarrow-dataset=15.0.0
  - libarrow-flight=15.0.0
  - libarrow-flight-sql=15.0.0
  - libarrow-gandiva=15.0.0
  - libarrow-substrait=15.0.0
  - libass=0.17.1
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.5.0
  - libdeflate=1.19
  - libdrm=2.4.114
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.5.0
  - libffi=3.4.2
  - libflac=1.4.3
  - libgcc-ng=13.2.0
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libglib=2.78.3
  - libgoogle-cloud=2.12.0
  - libgrpc=1.59.3
  - libhwloc=2.9.3
  - libiconv=1.17
  - libidn2=2.3.7
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - libllvm15=15.0.7
  - libnghttp2=1.58.0
  - libnl=3.9.0
  - libnsl=2.0.1
  - libnuma=2.0.16
  - libogg=1.3.4
  - libopenvino=2023.2.0
  - libopenvino-auto-batch-plugin=2023.2.0
  - libopenvino-auto-plugin=2023.2.0
  - libopenvino-hetero-plugin=2023.2.0
  - libopenvino-intel-cpu-plugin=2023.2.0
  - libopenvino-intel-gpu-plugin=2023.2.0
  - libopenvino-ir-frontend=2023.2.0
  - libopenvino-onnx-frontend=2023.2.0
  - libopenvino-paddle-frontend=2023.2.0
  - libopenvino-pytorch-frontend=2023.2.0
  - libopenvino-tensorflow-frontend=2023.2.0
  - libopenvino-tensorflow-lite-frontend=2023.2.0
  - libopus=1.3.1
  - libparquet=15.0.0
  - libpciaccess=0.17
  - libpng=1.6.39
  - libprotobuf=4.24.4
  - libre2-11=2023.06.02
  - librosa=0.10.1
  - libsndfile=1.2.2
  - libsodium=1.0.18
  - libsqlite=3.44.2
  - libssh2=1.11.0
  - libstdcxx-ng=13.2.0
  - libtasn1=4.19.0
  - libthrift=0.19.0
  - libtiff=4.6.0
  - libunistring=0.9.10
  - libutf8proc=2.8.0
  - libuuid=2.38.1
  - libva=2.20.0
  - libvorbis=1.3.7
  - libvpx=1.13.1
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxcrypt=4.4.36
  - libxml2=2.12.4
  - libzlib=1.2.13
  - llvm-openmp=15.0.7
  - llvmlite=0.41.1
  - lz4-c=1.9.4
  - markdown=3.5.2
  - markupsafe=2.1.4
  - matplotlib-base=3.8.2
  - matplotlib-inline=0.1.6
  - mistune=3.0.2
  - mkl=2022.2.1
  - ml_dtypes=0.2.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpg123=1.32.4
  - mpmath=1.3.0
  - msgpack-python=1.0.7
  - multidict=6.0.4
  - multiprocess=0.70.15
  - munkres=1.1.4
  - nbclient=0.8.0
  - nbconvert-core=7.14.2
  - nbformat=5.9.2
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - nettle=3.9.1
  - networkx=3.2.1
  - notebook-shim=0.2.3
  - numba=0.58.1
  - numpy=1.26.3
  - oauthlib=3.2.2
  - ocl-icd=2.3.1
  - ocl-icd-system=1.0.0
  - openh264=2.4.0
  - openjpeg=2.5.0
  - openssl=3.2.1
  - opt_einsum=3.3.0
  - orc=1.9.2
  - overrides=7.7.0
  - p11-kit=0.24.1
  - packaging=23.2
  - pandas=2.2.0
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pcre2=10.42
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=10.2.0
  - pip=23.3.2
  - pixman=0.43.2
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.2.0
  - pooch=1.8.0
  - prometheus_client=0.19.0
  - prompt-toolkit=3.0.42
  - protobuf=4.24.4
  - psutil=5.9.8
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pugixml=1.14
  - pure_eval=0.2.2
  - pyarrow=15.0.0
  - pyarrow-hotfix=0.6
  - pyasn1=0.5.1
  - pyasn1-modules=0.3.0
  - pycparser=2.21
  - pygments=2.17.2
  - pyjwt=2.8.0
  - pyopenssl=24.0.0
  - pyparsing=3.1.1
  - pysocks=1.7.1
  - pysoundfile=0.12.1
  - python=3.11.7
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.19.1
  - python-flatbuffers=23.5.26
  - python-json-logger=2.0.7
  - python-tzdata=2023.4
  - python-xxhash=3.4.1
  - python_abi=3.11
  - pytorch=2.2.0
  - pytorch-mutex=1.0
  - pytz=2023.4
  - pyu2f=0.1.5
  - pyyaml=6.0.1
  - pyzmq=25.1.2
  - rdma-core=50.0
  - re2=2023.06.02
  - readline=8.2
  - referencing=0.33.0
  - regex=2023.12.25
  - requests=2.31.0
  - requests-oauthlib=1.3.1
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.17.1
  - rsa=4.9
  - s2n=1.4.1
  - safetensors=0.3.3
  - scikit-learn=1.4.0
  - scipy=1.12.0
  - send2trash=1.8.2
  - setuptools=69.0.3
  - six=1.16.0
  - snappy=1.1.10
  - sniffio=1.3.0
  - soupsieve=2.5
  - soxr=0.1.3
  - soxr-python=0.3.7
  - stack_data=0.6.2
  - svt-av1=1.8.0
  - sympy=1.12
  - tbb=2021.11.0
  - tensorboard=2.15.1
  - tensorboard-data-server=0.7.0
  - tensorflow=2.15.0
  - tensorflow-base=2.15.0
  - tensorflow-estimator=2.15.0
  - termcolor=2.4.0
  - terminado=0.18.0
  - threadpoolctl=3.2.0
  - tinycss2=1.2.1
  - tk=8.6.13
  - tokenizers=0.15.1
  - tomli=2.0.1
  - torchaudio=2.2.0
  - torchvision=0.17.0
  - tornado=6.3.3
  - tqdm=4.66.1
  - traitlets=5.14.1
  - transformers=4.37.1
  - types-python-dateutil=2.8.19.20240106
  - typing-extensions=4.9.0
  - typing_extensions=4.9.0
  - typing_utils=0.1.0
  - tzdata=2023d
  - ucx=1.15.0
  - uri-template=1.3.0
  - urllib3=2.2.0
  - wcwidth=0.2.13
  - webcolors=1.13
  - webencodings=0.5.1
  - websocket-client=1.7.0
  - werkzeug=3.0.1
  - wheel=0.42.0
  - widgetsnbextension=4.0.9
  - wrapt=1.14.1
  - x264=1!164.3095
  - x265=3.5
  - xorg-fixesproto=5.0
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.7
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxrender=0.9.11
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xxhash=0.8.2
  - xz=5.2.6
  - yaml=0.2.5
  - yarl=1.9.4
  - zeromq=4.3.5
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
